/* eslint-disable */
// this file is auto generated by build/build-icons.js

export interface IconMap {
  ArrowDown: string;
  ArrowLeft: string;
  ArrowRight: string;
  ArrowUp: string;
  Attention: string;
  CheckOne: string;
  Check: string;
  Circle: string;
  CloseOne: string;
  Close: string;
  Default: string;
  Error: string;
  Filter: string;
  Info: string;
  Loading: string;
  PartialCheck: string;
  QuestionMark: string;
  RadioUncheck: string;
  Radio: string;
  SquareCheckOne: string;
  SquareUncheck: string;
  Success: string;
  Triangular: string;
  Warning: string;
}

export const allIcons: IconMap = {
  ArrowDown: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 18 18"><mask id="okee-icon-arrow-down-a" width="18" height="18" x="0" y="0" maskUnits="userSpaceOnUse"><path fill="#fff" d="M18 0h18v18H18z" transform="rotate(90 18 0)"/></mask><g mask="url(#okee-icon-arrow-down-a)"><path fill-rule="evenodd" d="M8.416 12.584L3.113 7.28a.75.75 0 011.06-1.06l4.774 4.773L13.72 6.22a.75.75 0 111.06 1.06l-5.303 5.304a.75.75 0 01-1.06 0z" clip-rule="evenodd"/></g></svg>`,
  ArrowLeft: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 18 18"><mask id="okee-icon-arrow-left-a" width="18" height="18" x="0" y="0" maskUnits="userSpaceOnUse"><path fill="#fff" d="M18 18h18v18H18z" transform="rotate(-180 18 18)"/></mask><g mask="url(#okee-icon-arrow-left-a)"><path fill-rule="evenodd" d="M5.416 8.416l5.304-5.303a.75.75 0 111.06 1.06L7.007 8.948l4.773 4.773a.75.75 0 11-1.06 1.06L5.416 9.477a.75.75 0 010-1.06z" clip-rule="evenodd"/></g></svg>`,
  ArrowRight: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 18 18"><mask id="okee-icon-arrow-right-a" width="18" height="18" x="0" y="0" maskUnits="userSpaceOnUse"><path fill="#fff" d="M0 0h18v18H0z"/></mask><g mask="url(#okee-icon-arrow-right-a)"><path fill-rule="evenodd" d="M12.584 9.584L7.28 14.887a.75.75 0 01-1.06-1.06l4.773-4.774L6.22 4.28a.75.75 0 011.06-1.06l5.304 5.303a.75.75 0 010 1.06z" clip-rule="evenodd"/></g></svg>`,
  ArrowUp: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 18 18"><mask id="okee-icon-arrow-up-a" width="18" height="18" x="0" y="0" maskUnits="userSpaceOnUse"><path fill="#fff" d="M0 18h18v18H0z" transform="rotate(-90 0 18)"/></mask><g mask="url(#okee-icon-arrow-up-a)"><path fill-rule="evenodd" d="M9.584 5.416l5.303 5.304a.75.75 0 11-1.06 1.06L9.052 7.007 4.28 11.78a.75.75 0 01-1.06-1.06l5.303-5.304a.75.75 0 011.06 0z" clip-rule="evenodd"/></g></svg>`,
  Attention: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 16 16"><path fill="#fff" fill-opacity=".01" d="M0 0h16v16H0z"/><path fill-rule="evenodd" d="M13.185 13.185A7.31 7.31 0 018 15.333a7.31 7.31 0 01-5.185-2.148A7.31 7.31 0 01.667 8c0-1.97.782-3.82 2.148-5.185A7.311 7.311 0 018 .667c1.97 0 3.82.782 5.185 2.148A7.31 7.31 0 0115.333 8a7.31 7.31 0 01-2.148 5.185zM7.333 4v5.333a.667.667 0 001.334 0V4a.667.667 0 00-1.334 0zM8 12.333a.833.833 0 100-1.666.833.833 0 000 1.666z" clip-rule="evenodd"/></svg>`,
  CheckOne: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 20 20"><path fill="#fff" fill-opacity=".01" d="M20 0H0v20h20V0z"/><path d="M10 18.333a8.308 8.308 0 005.893-2.44A8.308 8.308 0 0018.333 10a8.307 8.307 0 00-2.44-5.893A8.307 8.307 0 0010 1.667a8.307 8.307 0 00-5.892 2.44A8.307 8.307 0 001.667 10c0 2.301.933 4.384 2.44 5.893A8.307 8.307 0 0010 18.333z"/><path d="M3.518 3.518A9.14 9.14 0 0110 .833a9.14 9.14 0 016.482 2.685A9.14 9.14 0 0119.166 10a9.14 9.14 0 01-2.684 6.482A9.14 9.14 0 0110 19.167a9.14 9.14 0 01-6.482-2.685A9.14 9.14 0 01.833 10a9.14 9.14 0 012.685-6.482zM10 2.5a7.474 7.474 0 00-5.304 2.197A7.474 7.474 0 002.5 10c0 2.071.838 3.945 2.196 5.303A7.474 7.474 0 0010 17.5a7.474 7.474 0 005.303-2.197A7.474 7.474 0 0017.5 10a7.474 7.474 0 00-2.197-5.303A7.474 7.474 0 0010 2.5z" clip-rule="evenodd"/><path fill="#FAFBFD" fill-rule="evenodd" d="M14.756 6.91a.833.833 0 010 1.18l-5 5a.833.833 0 01-1.179 0l-2.5-2.5a.833.833 0 011.179-1.18l1.91 1.912 4.411-4.411a.833.833 0 011.179 0z" clip-rule="evenodd"/></svg>`,
  Check: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 20 20"><path d="M15.424 4.617a1.138 1.138 0 011.605 0 1.137 1.137 0 010 1.607l-8.21 8.21a1.136 1.136 0 01-1.605-1.606l8.21-8.211z" clip-rule="evenodd"/><path d="M8.81 12.74a1.217 1.217 0 010 1.678 1.13 1.13 0 01-1.63 0l-3.986-3.916a1.212 1.212 0 010-1.678 1.13 1.13 0 011.629 0L8.81 12.74z" clip-rule="evenodd"/></svg>`,
  Circle: `<svg width="100%" height="100%" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 1.5a7.5 7.5 0 100 15 7.5 7.5 0 000-15zM.5 9a8.5 8.5 0 1117 0 8.5 8.5 0 01-17 0z" fill="#DCDCDC"/><path fill-rule="evenodd" clip-rule="evenodd" d="M16.5 9A7.5 7.5 0 009 1.5v-1A8.5 8.5 0 0117.5 9h-1z"/></svg>`,
  CloseOne: `<svg width="100%" height="100%" viewBox="0 0 16 16"><path fill="#fff" fill-opacity=".01" d="M0 0h16v16H0z"/><path fill-rule="evenodd" d="M15.333 8A7.333 7.333 0 11.667 8a7.333 7.333 0 0114.666 0zm-9.69-1.414L7.057 8 5.643 9.414a.667.667 0 10.943.943L8 8.943l1.414 1.414a.667.667 0 10.943-.943L8.943 8l1.414-1.414a.667.667 0 10-.943-.943L8 7.057 6.586 5.643a.667.667 0 10-.943.943z" clip-rule="evenodd"/></svg>`,
  Close: `<svg width="100%" height="100%" viewBox="0 0 48 48">
<path fill-rule="evenodd" clip-rule="evenodd" d="M15.4142 12.5858C14.6332 11.8047 13.3668 11.8047 12.5858 12.5858C11.8047 13.3668 11.8047 14.6332 12.5858 15.4142L21.1716 24L12.5858 32.5858C11.8047 33.3668 11.8047 34.6332 12.5858 35.4142C13.3668 36.1953 14.6332 36.1953 15.4142 35.4142L24 26.8284L32.5858 35.4142C33.3668 36.1953 34.6332 36.1953 35.4142 35.4142C36.1953 34.6332 36.1953 33.3668 35.4142 32.5858L26.8284 24L35.4142 15.4142C36.1953 14.6332 36.1953 13.3668 35.4142 12.5858C34.6332 11.8047 33.3668 11.8047 32.5858 12.5858L24 21.1716L15.4142 12.5858Z"/>
</svg>
`,
  Default: `<svg width="100%" height="100%" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.04 3.375a7.5 7.5 0 1011.163 1.407l.826-.563A8.5 8.5 0 113.378 2.626l.661.749z"/></svg>`,
  Error: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 64 64"><g fill="none" fill-rule="evenodd" stroke="#FFF" stroke-linejoin="round" stroke-width="3.6" transform="translate(2 2)"><circle cx="30" cy="30" r="30"/><path stroke-linecap="round" d="M38.485 21.515l-16.97 16.97M21.515 21.515l16.97 16.97"/></g></svg>`,
  Filter: `<svg width="100%" height="100%" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12 0H0V12H12V0Z" fill="white" fill-opacity="0.01"/>
  <path d="M1.5 2.25L5.1 6.45444V9.61111L6.9 10.5V6.45444L10.5 2.25H1.5Z" fill="#C1C1C1" stroke="#C1C1C1" stroke-linejoin="round"/>
</svg>
`,
  Info: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 16 16"><path fill="#fff" fill-opacity=".01" d="M0 0h16v16H0z"/><path fill-rule="evenodd" d="M13.185 13.185A7.31 7.31 0 018 15.333a7.31 7.31 0 01-5.185-2.148A7.31 7.31 0 01.667 8c0-1.97.782-3.82 2.148-5.185A7.311 7.311 0 018 .667c1.97 0 3.82.782 5.185 2.148A7.31 7.31 0 0115.333 8a7.31 7.31 0 01-2.148 5.185zM7 10.668h.5V7.333A.667.667 0 117.5 6h.667c.368 0 .666.299.666.667v4h.5a.667.667 0 010 1.333H7a.667.667 0 010-1.333zM8.833 4.5a.833.833 0 10-1.666 0 .833.833 0 001.666 0z" clip-rule="evenodd"/></svg>`,
  Loading: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 64 64"><path fill="none" fill-rule="evenodd" stroke="#FFF" stroke-linecap="round" stroke-width="3" d="M2 31c0 17.12 13.88 31 31 31"/></svg>`,
  PartialCheck: `<svg width="100%" height="100%" viewBox="0 0 12 12"><path d="M1.5 6H10.5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>`,
  QuestionMark: `<svg width="100%" height="100%" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M7.00008 2.0013C4.23866 2.0013 2.00008 4.23988 2.00008 7.0013C2.00008 9.76273 4.23866 12.0013 7.00008 12.0013C9.76151 12.0013 12.0001 9.76273 12.0001 7.0013C12.0001 4.23988 9.76151 2.0013 7.00008 2.0013ZM0.666748 7.0013C0.666748 3.5035 3.50228 0.667969 7.00008 0.667969C10.4979 0.667969 13.3334 3.5035 13.3334 7.0013C13.3334 10.4991 10.4979 13.3346 7.00008 13.3346C3.50228 13.3346 0.666748 10.4991 0.666748 7.0013Z" fill="black" fill-opacity="0.42"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M4.64302 4.30834C5.2455 3.70586 6.07975 3.33203 7.00004 3.33203C7.92033 3.33203 8.75458 3.70586 9.35706 4.30834C9.61741 4.56869 9.61741 4.9908 9.35706 5.25115C9.09671 5.5115 8.6746 5.5115 8.41425 5.25115C8.05159 4.88849 7.55251 4.66536 7.00004 4.66536C6.44757 4.66536 5.94848 4.88849 5.58583 5.25115C5.32548 5.5115 4.90337 5.5115 4.64302 5.25115C4.38267 4.9908 4.38267 4.56869 4.64302 4.30834Z" fill="black" fill-opacity="0.42"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M10.6026 10.6042C10.8629 10.3439 11.285 10.3439 11.5454 10.6042L14.3738 13.4326C14.6342 13.693 14.6342 14.1151 14.3738 14.3755C14.1135 14.6358 13.6913 14.6358 13.431 14.3755L10.6026 11.547C10.3422 11.2867 10.3422 10.8646 10.6026 10.6042Z" fill="black" fill-opacity="0.42"/>
</svg>
`,
  RadioUncheck: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 20 20"><path fill-opacity=".01" d="M20 0H0v20h20V0z"/><path d="M3.518 3.518A9.14 9.14 0 0110 .833a9.14 9.14 0 016.482 2.685A9.14 9.14 0 0119.166 10a9.14 9.14 0 01-2.684 6.482A9.14 9.14 0 0110 19.167a9.14 9.14 0 01-6.482-2.685A9.14 9.14 0 01.833 10a9.14 9.14 0 012.685-6.482zM10 2.5a7.474 7.474 0 00-5.304 2.197A7.474 7.474 0 002.5 10c0 2.071.838 3.945 2.196 5.303A7.474 7.474 0 0010 17.5a7.474 7.474 0 005.303-2.197A7.474 7.474 0 0017.5 10a7.474 7.474 0 00-2.197-5.303A7.474 7.474 0 0010 2.5z" clip-rule="evenodd"/></svg>`,
  Radio: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 20 20"><path fill-opacity=".01" d="M20 0H0v20h20V0z"/><path fill-rule="evenodd" d="M10 16a6 6 0 100-12 6 6 0 000 12z" clip-rule="evenodd"/><path fill="#EBEBEB" fill-rule="evenodd" d="M3.518 3.518A9.14 9.14 0 0110 .833a9.14 9.14 0 016.482 2.685A9.14 9.14 0 0119.166 10a9.14 9.14 0 01-2.684 6.482A9.14 9.14 0 0110 19.167a9.14 9.14 0 01-6.482-2.685A9.14 9.14 0 01.833 10a9.14 9.14 0 012.685-6.482zM10 2.5a7.474 7.474 0 00-5.304 2.197A7.474 7.474 0 002.5 10c0 2.071.838 3.945 2.196 5.303A7.474 7.474 0 0010 17.5a7.474 7.474 0 005.303-2.197A7.474 7.474 0 0017.5 10a7.474 7.474 0 00-2.197-5.303A7.474 7.474 0 0010 2.5z" clip-rule="evenodd"/></svg>`,
  SquareCheckOne: `<svg width="100%" height="100%" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <rect x="2" y="2" width="20" height="20" rx="4"/>
  <path d="M8 12L11 15L17 9" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`,
  SquareUncheck: `
<svg width="100%" height="100%" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M2.25 6C2.25 3.92893 3.92893 2.25 6 2.25H18C20.0711 2.25 21.75 3.92893 21.75 6V18C21.75 20.0711 20.0711 21.75 18 21.75H6C3.92893 21.75 2.25 20.0711 2.25 18V6ZM6 3.75C4.75736 3.75 3.75 4.75736 3.75 6V18C3.75 19.2426 4.75736 20.25 6 20.25H18C19.2426 20.25 20.25 19.2426 20.25 18V6C20.25 4.75736 19.2426 3.75 18 3.75H6Z" />
</svg>
`,
  Success: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 66 66"><g fill="none" fill-rule="evenodd" stroke="#FFF" transform="translate(2 2)"><circle cx="31" cy="31" r="31" stroke-width="3"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M48 24L28.55 42.47 16.53 30.45"/></g></svg>`,
  Triangular: `<svg width="100%" height="100%" viewBox="0 0 14 14"><path d="M5.54297 3.5L9.04297 7L5.54297 10.5L5.54297 3.5Z" stroke-width="1.16667" stroke-linejoin="round"/></svg>`,
  Warning: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 66 66"><g fill="none" fill-rule="evenodd" transform="translate(2 2)"><circle cx="31" cy="31" r="31" stroke="#FFF" stroke-width="3"/><path fill="#FFF" d="M31 13a2.944 2.944 0 0 1 2.943 3l-.368 19.49A2.558 2.558 0 0 1 31.018 38a2.561 2.561 0 0 1-2.561-2.51L28.06 16A2.94 2.94 0 0 1 31 13z"/><circle cx="31" cy="46" r="3" fill="#FFF"/></g></svg>`,
};
